[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pysie-sdk"
version = "0.1.4"
description = "This is a simple SDK for get the principal Mexican financial indicators"
readme = "README.md"
requires-python = ">=3.8"
license = {file = "LICENSE"}
authors = [{name = "Alejandro Betancourt", email = "fierroformo@gmail.com"}]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent"
]
dependencies = [
    "requests",
]

[project.urls]
"Homepage" = "https://github.com/fierroformo/pysie"
"Bug Tracker" = "https://github.com/fierroformo/pysie/issues"



ğŸ’µ Â¡Actualice pysie-sdk! y ahora ya puedes consultar la cantidad de billetes falsos detectados por denominaciÃ³n en el Ãºltimo aÃ±o, con datos oficiales del Banco de MÃ©xico.



Esta nueva funcionalidad permite acceder fÃ¡cilmente a informaciÃ³n clave para entender el impacto de la falsificaciÃ³n de efectivo en nuestro paÃ­s. Por ejemplo, en el Ãºltimo aÃ±o se detectaron mÃ¡s de 176 mil billetes falsos de $500, lo que resalta la importancia de estar informados y alerta.



ğŸ“Š El uso de efectivo sigue siendo el medio predominante para transacciones comerciales en MÃ©xico, especialmente entre sectores con menor acceso a servicios bancarios. Esto plantea un reto para la seguridad econÃ³mica, pero tambiÃ©n una gran oportunidad para las fintech.



ğŸš€ Las empresas de tecnologÃ­a financiera pueden jugar un papel crucial al digitalizar pagos y reducir la dependencia del efectivo, ofreciendo soluciones mÃ¡s seguras, accesibles y eficientes para millones de personas.



ğŸ” Mientras tanto, es importante que los usuarios estÃ©n atentos a los billetes que reciben y se informen sobre cÃ³mo identificar posibles falsificaciones.



SDK ğŸ  https://pypi.org/project/pysie-sdk/



#Fintech #Banxico #pysie #PagosDigitales #TransformaciÃ³nDigital #BilletesFalsos #SeguridadFinanciera #MÃ©xico #Backend #Python



4 principios basicos de poo

normalizacion, ventajas y desventajas

que es una transacciÃ³n (atomicidad, consistencia, aislamiento, durabilidad)